const Types = {
  USER: {
    SET_API_TOKEN: 'SET_API_TOKEN',

    LOGOUT: 'LOGOUT',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOAD_PROFILE_PENDING: 'LOAD_PROFILE_PENDING',
    LOAD_PROFILE_SUCCESS: 'LOAD_PROFILE_SUCCESS',
    LOAD_PROFILE_FAILURE: 'LOAD_PROFILE_FAILURE',

    CHANGE_PASSWORD_PENDING: 'CHANGE_PASSWORD_PENDING',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
  },
  TOAST: {
    ADD_TOAST: 'ADD_TOAST',
    REMOVE_TOAST: 'REMOVE_TOAST',
  },
};
export default Types;
